### ISSUE TITLE
Weather forecast from the past (timezones)

### ISSUE THREAD

**Issue by sacsar** [abtrout/forecats#9]
This may be something solvable via #5. At 10am Thursday (Central Time), if I look at the daily forecast for somewhere in the UK, the first day I see is Wednesday. Somewhere along the line, the timezone is being adjusted twice.

**Comment by abtrout** [comment]
Interesting (and hi!). I currently see exactly the behavior you're describing when I search for London, but see expected behavior (Thursday being the first day) when I search for San Francisco.

I am making ordinary requests to the Forecast API (no adjustments for timezones, etc). According to their API docs, timestamps are UNIX epoch UTC/GMT. Daily datapoints include a UTC/GMT timestamp for midnight at whatever location "today". Midnight in London (GMT-1) is the previous day in Austin (GMT-5).

I think you're right about #5. Forecats needs to adjust timestamps to the timezone at the searched-location rather than the users current location. It might be simpler, though. As it turns out, Forecast returns a `timezone` at the searched location with weather requests!

**Comment by abtrout** [comment]
Fixed. Though (note to self) #8 is potentially more important now.
